services:
  postgresql:
    container_name: library-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: library_service
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

  library-apigateway-server:
    container_name: library-apigateway-server
    build:
      context: library-apigateway-server
      dockerfile: ./Dockerfile
    environment:
      CONFIG_SERVER_HOSTNAME: library-config-server
      DISCOVERY_SERVER_HOSTNAME: library-discovery-server
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      library-config-server:
        condition: service_healthy
    restart: unless-stopped

  library-config-server:
    container_name: library-config-server
    build:
      context: library-config-server
      dockerfile: ./Dockerfile
    environment:
      MAIN_HOSTNAME: library-main-server
      DISCOVERY_SERVER_HOSTNAME: library-discovery-server
      DB_HOSTNAME: postgresql
    ports:
      - "8888:8888"
    networks:
      - default
    healthcheck:
      test: "curl --fail --silent http://localhost:8888/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  library-discovery-server:
    container_name: library-discovery-server
    build:
      context: library-discovery-server
      dockerfile: ./Dockerfile
    environment:
      CONFIG_SERVER_HOSTNAME: library-config-server
    ports:
      - "8761:8761"
    networks:
      - default
    restart: unless-stopped

  library-auth-service:
    container_name: library-auth-service
    build:
      context: library-auth-service
      dockerfile: ./Dockerfile
    environment:
      CONFIG_SERVER_HOSTNAME: library-config-server
      DISCOVERY_SERVER_HOSTNAME: library-discovery-server
    ports:
      - "8532:8532"
    networks:
      - default
    depends_on:
      library-config-server:
        condition: service_healthy
      library-apigateway-server:
        condition: service_started
      library-discovery-server:
        condition: service_started
    restart: unless-stopped

  library-main-service:
    container_name: library-main-service
    build:
      context: library-main-service
      dockerfile: ./Dockerfile
    environment:
      CONFIG_SERVER_HOSTNAME: library-config-server
      DISCOVERY_SERVER_HOSTNAME: library-discovery-server
      AUTH_SERVER_HOSTNAME: library-auth-service
    ports:
      - "8991:8991"
    networks:
      - default
    depends_on:
      library-config-server:
        condition: service_healthy
      library-apigateway-server:
        condition: service_started
      library-discovery-server:
        condition: service_started
      library-auth-service:
        condition:  service_started
    restart: unless-stopped

  library-reservation-service:
    container_name: library-reservation-service
    build:
      context: library-reservation-service
      dockerfile: ./Dockerfile
    environment:
      CONFIG_SERVER_HOSTNAME: library-config-server
      DISCOVERY_SERVER_HOSTNAME: library-discovery-server
      AUTH_SERVER_HOSTNAME: library-auth-service
    ports:
      - "8501:8501"
    networks:
      - default
    depends_on:
      library-config-server:
        condition: service_healthy
      library-apigateway-server:
        condition: service_started
      library-discovery-server:
        condition: service_started
      library-auth-service:
        condition: service_started
    restart: unless-stopped

networks:
  default:

volumes:
  postgres:
  pgadmin: