-- liquibase formatted sql

-- changeset Alexey_Bobrovich:1726125019524-1
CREATE TABLE authors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

-- changeset Alexey_Bobrovich:1726125019524-2
CREATE TABLE book_author
(
    author_id BIGINT NOT NULL,
    book_id   BIGINT NOT NULL
);

-- changeset Alexey_Bobrovich:1726125019524-3
CREATE TABLE book_genre
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL
);

-- changeset Alexey_Bobrovich:1726125019524-4
CREATE TABLE books
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    isbn        VARCHAR(255),
    title       VARCHAR(255),
    description VARCHAR(1000),
    quantity    INTEGER,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

-- changeset Alexey_Bobrovich:1726125019524-5
CREATE TABLE genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

-- changeset Alexey_Bobrovich:1726125019524-8
ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);

-- changeset Alexey_Bobrovich:1726125019524-9
ALTER TABLE genres
    ADD CONSTRAINT uc_genres_name UNIQUE (name);

-- changeset Alexey_Bobrovich:1726125019524-10
ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_author FOREIGN KEY (author_id) REFERENCES authors (id);

-- changeset Alexey_Bobrovich:1726125019524-11
ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES books (id);

-- changeset Alexey_Bobrovich:1726125019524-12
ALTER TABLE book_genre
    ADD CONSTRAINT fk_boogen_on_book FOREIGN KEY (book_id) REFERENCES books (id);

-- changeset Alexey_Bobrovich:1726125019524-13
ALTER TABLE book_genre
    ADD CONSTRAINT fk_boogen_on_book_genre FOREIGN KEY (genre_id) REFERENCES genres (id);

